### ISSUE TITLE
Переменные, цвета, scss, css custom properties

### ISSUE THREAD

**Issue by sglazov** [sglazov/spt#9]
## Что

Чего-то вообще не нравится стартовый набор переменных, переопреляется криво, не логично.

## Что делать

1. Отдельные категории (цвета, эффекты, тени), без фанатизма и избыточности
1. Карты? Как, например, для `z-index` — очень удобно
1. Разворачивать циклом в набор custom properties
1. Всё базовое определять только в scss-варианте
1. Выкинуть все `! glob`?

Нравится такая идея:

```scss
// variables.scss
$colors: (
  "black"       : #1f1f1f,
  "text"        : #000000,
  "brand"       : #ff9900,
  "accent"      : #f5a623,
  "accent-500 " : transparentize(#f5a623, 0.5),
  "title"       : #333333,
  "hover"       : #f5a623
  // etc...
);
// base.scss
:root {
  @each $key, $value in $colors {
    --#{$key}: #{$value};
  }
}
```
